/**
 * TypeScript-side cross-system consistency test.
 *
 * Loads the same consistency-test-rounds.jsonl fixture used by the Python tests,
 * computes standings via the TypeScript standings module, and asserts the result
 * matches consistency-expected.json (the golden file generated by Python).
 *
 * This is the critical cross-system test: if Python and TypeScript produce
 * different standings from the same input, this test fails.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import type { RoundResult } from '../index.js';
import {
  deduplicate,
  scorableEntries,
  computeStandings,
  computeDivergences,
  computeClosestCalls,
  computeDimensionTotals,
  computeAll,
} from '../standings.js';

const FIXTURE_DIR = resolve(__dirname, '../../../pipeline/tests/cross-system');
const FIXTURE_PATH = resolve(FIXTURE_DIR, 'consistency-test-rounds.jsonl');
const GOLDEN_PATH = resolve(FIXTURE_DIR, 'consistency-expected.json');

function loadFixture(): RoundResult[] {
  const content = readFileSync(FIXTURE_PATH, 'utf-8');
  return content
    .split('\n')
    .filter(line => line.trim())
    .map(line => JSON.parse(line) as RoundResult);
}

function loadGolden(): Record<string, unknown> {
  return JSON.parse(readFileSync(GOLDEN_PATH, 'utf-8'));
}

describe('Cross-System Consistency (TypeScript)', () => {
  const rawEntries = loadFixture();
  const expected = loadGolden();
  const entries = deduplicate(rawEntries);

  describe('metadata', () => {
    it('raw entry count matches', () => {
      expect(rawEntries.length).toBe((expected.metadata as Record<string, number>).total_raw_entries);
    });

    it('dedup count matches', () => {
      expect(entries.length).toBe((expected.metadata as Record<string, number>).total_after_dedup);
    });

    it('scorable count matches', () => {
      const scorable = scorableEntries(entries);
      expect(scorable.length).toBe((expected.metadata as Record<string, number>).total_scorable);
    });
  });

  describe('deduplication', () => {
    it('removes agent entry when score exists for R09 alpha', () => {
      const r09Alpha = entries.filter(e => e.round_id === 'R09' && e.competitor === 'alpha');
      expect(r09Alpha).toHaveLength(1);
      expect(r09Alpha[0].source).toBe('score');
      expect(r09Alpha[0].total).toBe(11);
    });

    it('preserves agent-only entry for R10 gamma', () => {
      const r10Gamma = entries.filter(e => e.round_id === 'R10' && e.competitor === 'gamma');
      expect(r10Gamma).toHaveLength(1);
      expect(r10Gamma[0].source).toBe('agent');
      expect(r10Gamma[0].total).toBeUndefined();
    });
  });

  describe('overall standings', () => {
    it('matches golden file exactly', () => {
      const standings = computeStandings(entries);
      expect(standings).toEqual(expected.overall);
    });
  });

  describe('by_codebase standings', () => {
    it('matches golden file for all codebases', () => {
      const scorable = scorableEntries(entries);
      const byCodebase: Record<string, unknown[]> = {};
      const groups = new Map<string, RoundResult[]>();
      for (const e of scorable) {
        const g = groups.get(e.codebase);
        if (g) g.push(e);
        else groups.set(e.codebase, [e]);
      }
      for (const [codebase, group] of [...groups.entries()].sort(([a], [b]) => a.localeCompare(b))) {
        byCodebase[codebase] = computeStandings(group);
      }
      expect(byCodebase).toEqual(expected.by_codebase);
    });
  });

  describe('by_category standings', () => {
    it('matches golden file for all categories', () => {
      const scorable = scorableEntries(entries);
      const byCategory: Record<string, unknown[]> = {};
      const groups = new Map<string, RoundResult[]>();
      for (const e of scorable) {
        const cat = e.query_category ?? 'unknown';
        const g = groups.get(cat);
        if (g) g.push(e);
        else groups.set(cat, [e]);
      }
      for (const [cat, group] of [...groups.entries()].sort(([a], [b]) => a.localeCompare(b))) {
        byCategory[cat] = computeStandings(group);
      }
      expect(byCategory).toEqual(expected.by_category);
    });
  });

  describe('divergences', () => {
    it('matches golden file', () => {
      const divergences = computeDivergences(entries);
      expect(divergences).toEqual(expected.divergences);
    });

    it('has spread=2 for gray boundary', () => {
      const divergences = computeDivergences(entries);
      const gray = divergences.filter(d => d.divergence_signal === 'gray');
      expect(gray).toHaveLength(1);
      expect(gray[0].spread).toBe(2);
    });

    it('has spread=5 for signal boundary', () => {
      const divergences = computeDivergences(entries);
      const signal = divergences.filter(d => d.divergence_signal === 'signal');
      expect(signal.some(d => d.spread === 5)).toBe(true);
    });
  });

  describe('closest_calls', () => {
    it('matches golden file', () => {
      const closest = computeClosestCalls(entries);
      expect(closest).toEqual(expected.closest_calls);
    });

    it('includes margin=0 ties and margin=1', () => {
      const closest = computeClosestCalls(entries);
      const margins = closest.map(c => c.margin);
      expect(margins).toContain(0);
      expect(margins).toContain(1);
    });
  });

  describe('dimension_totals', () => {
    it('matches golden file', () => {
      const dims = computeDimensionTotals(entries);
      expect(dims).toEqual(expected.dimension_totals);
    });
  });

  describe('computeAll integration', () => {
    it('full computation matches golden file', () => {
      const result = computeAll(rawEntries, 'consistency-test-rounds.jsonl');
      expect(result).toEqual(expected);
    });
  });
});
