import type { RoundResult } from '@arena/schemas';

/**
 * Mock round results representing a 4-round competition between
 * "maproom" and "explore" across two codebases.
 */
export const mockRounds: RoundResult[] = [
  {
    schema_version: 1,
    round_id: 'R01',
    competitor: 'maproom',
    round_type: 'regular',
    codebase: 'django',
    phase: 1,
    query_category: 'flow',
    precision: 3,
    recall: 4,
    insight: 2,
    total: 9,
    calls: 15,
    time_s: 120,
    source: 'score',
    round_winner: 'maproom',
    is_calibration: false,
    timestamp: '2025-01-01T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R01',
    competitor: 'explore',
    round_type: 'regular',
    codebase: 'django',
    phase: 1,
    query_category: 'flow',
    precision: 2,
    recall: 3,
    insight: 2,
    total: 7,
    calls: 22,
    time_s: 180,
    source: 'score',
    round_winner: 'maproom',
    is_calibration: false,
    timestamp: '2025-01-01T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R02',
    competitor: 'maproom',
    round_type: 'regular',
    codebase: 'django',
    phase: 1,
    query_category: 'pattern',
    precision: 2,
    recall: 2,
    insight: 3,
    total: 7,
    calls: 10,
    time_s: 90,
    source: 'score',
    round_winner: null,
    is_calibration: false,
    timestamp: '2025-01-02T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R02',
    competitor: 'explore',
    round_type: 'regular',
    codebase: 'django',
    phase: 1,
    query_category: 'pattern',
    precision: 3,
    recall: 2,
    insight: 2,
    total: 7,
    calls: 18,
    time_s: 150,
    source: 'score',
    round_winner: null,
    is_calibration: false,
    timestamp: '2025-01-02T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R03',
    competitor: 'maproom',
    round_type: 'regular',
    codebase: 'fastapi',
    phase: 1,
    query_category: 'boundary',
    precision: 4,
    recall: 3,
    insight: 3,
    total: 10,
    calls: 12,
    time_s: 100,
    source: 'score',
    round_winner: 'maproom',
    is_calibration: false,
    timestamp: '2025-01-03T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R03',
    competitor: 'explore',
    round_type: 'regular',
    codebase: 'fastapi',
    phase: 1,
    query_category: 'boundary',
    precision: 3,
    recall: 4,
    insight: 1,
    total: 8,
    calls: 25,
    time_s: 200,
    source: 'score',
    round_winner: 'maproom',
    is_calibration: false,
    timestamp: '2025-01-03T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R04',
    competitor: 'maproom',
    round_type: 'regular',
    codebase: 'fastapi',
    phase: 1,
    query_category: 'flow',
    precision: 2,
    recall: 2,
    insight: 1,
    total: 5,
    calls: 8,
    time_s: 60,
    source: 'score',
    round_winner: 'explore',
    is_calibration: false,
    timestamp: '2025-01-04T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R04',
    competitor: 'explore',
    round_type: 'regular',
    codebase: 'fastapi',
    phase: 1,
    query_category: 'flow',
    precision: 3,
    recall: 3,
    insight: 3,
    total: 9,
    calls: 20,
    time_s: 160,
    source: 'score',
    round_winner: 'explore',
    is_calibration: false,
    timestamp: '2025-01-04T10:00:00Z',
  },
];

/** Agent-only round (source='agent') — should be filtered out */
export const agentOnlyRound: RoundResult = {
  schema_version: 1,
  round_id: 'R05',
  competitor: 'maproom',
  round_type: 'regular',
  codebase: 'django',
  phase: 1,
  calls: 5,
  time_s: 30,
  source: 'agent',
  is_calibration: false,
};

/** Calibration round — should be filtered out */
export const calibrationRound: RoundResult = {
  schema_version: 1,
  round_id: 'CAL01',
  competitor: 'maproom',
  round_type: 'calibration',
  codebase: 'django',
  phase: 1,
  precision: 5,
  recall: 5,
  insight: 5,
  total: 15,
  calls: 10,
  time_s: 80,
  source: 'score',
  round_winner: 'maproom',
  is_calibration: true,
};

/** Duplicate round (same round_id+competitor as R01 maproom but later — should replace) */
export const duplicateRound: RoundResult = {
  schema_version: 1,
  round_id: 'R01',
  competitor: 'maproom',
  round_type: 'regular',
  codebase: 'django',
  phase: 1,
  query_category: 'flow',
  precision: 4,
  recall: 4,
  insight: 4,
  total: 12,
  calls: 14,
  time_s: 110,
  source: 'score',
  round_winner: 'maproom',
  is_calibration: false,
  timestamp: '2025-01-01T12:00:00Z',
};
