import type { RoundResult } from '@arena/schemas';

/**
 * Mock round results for development and demo purposes.
 * 8 rounds across 3 codebases, 2 competitors, variety of outcomes.
 */
export const MOCK_ROUNDS: RoundResult[] = [
  {
    schema_version: 1,
    round_id: 'R01',
    competitor: 'maproom',
    round_type: 'regular',
    codebase: 'django',
    phase: 1,
    query_category: 'flow',
    precision: 3,
    recall: 4,
    insight: 2,
    total: 9,
    calls: 15,
    time_s: 120,
    source: 'score',
    round_winner: 'maproom',
    is_calibration: false,
    timestamp: '2025-01-01T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R01',
    competitor: 'explore',
    round_type: 'regular',
    codebase: 'django',
    phase: 1,
    query_category: 'flow',
    precision: 2,
    recall: 3,
    insight: 2,
    total: 7,
    calls: 22,
    time_s: 180,
    source: 'score',
    round_winner: 'maproom',
    is_calibration: false,
    timestamp: '2025-01-01T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R02',
    competitor: 'maproom',
    round_type: 'regular',
    codebase: 'django',
    phase: 1,
    query_category: 'pattern',
    precision: 2,
    recall: 2,
    insight: 3,
    total: 7,
    calls: 10,
    time_s: 90,
    source: 'score',
    round_winner: null,
    is_calibration: false,
    timestamp: '2025-01-02T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R02',
    competitor: 'explore',
    round_type: 'regular',
    codebase: 'django',
    phase: 1,
    query_category: 'pattern',
    precision: 3,
    recall: 2,
    insight: 2,
    total: 7,
    calls: 18,
    time_s: 150,
    source: 'score',
    round_winner: null,
    is_calibration: false,
    timestamp: '2025-01-02T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R03',
    competitor: 'maproom',
    round_type: 'regular',
    codebase: 'fastapi',
    phase: 1,
    query_category: 'boundary',
    precision: 4,
    recall: 3,
    insight: 3,
    total: 10,
    calls: 12,
    time_s: 100,
    source: 'score',
    round_winner: 'maproom',
    is_calibration: false,
    timestamp: '2025-01-03T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R03',
    competitor: 'explore',
    round_type: 'regular',
    codebase: 'fastapi',
    phase: 1,
    query_category: 'boundary',
    precision: 3,
    recall: 4,
    insight: 1,
    total: 8,
    calls: 25,
    time_s: 200,
    source: 'score',
    round_winner: 'maproom',
    is_calibration: false,
    timestamp: '2025-01-03T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R04',
    competitor: 'maproom',
    round_type: 'regular',
    codebase: 'fastapi',
    phase: 1,
    query_category: 'flow',
    precision: 2,
    recall: 2,
    insight: 1,
    total: 5,
    calls: 8,
    time_s: 60,
    source: 'score',
    round_winner: 'explore',
    is_calibration: false,
    timestamp: '2025-01-04T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R04',
    competitor: 'explore',
    round_type: 'regular',
    codebase: 'fastapi',
    phase: 1,
    query_category: 'flow',
    precision: 3,
    recall: 3,
    insight: 3,
    total: 9,
    calls: 20,
    time_s: 160,
    source: 'score',
    round_winner: 'explore',
    is_calibration: false,
    timestamp: '2025-01-04T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R05',
    competitor: 'maproom',
    round_type: 'regular',
    codebase: 'mattermost-webapp',
    phase: 1,
    query_category: 'lifecycle',
    precision: 3,
    recall: 3,
    insight: 2,
    total: 8,
    calls: 18,
    time_s: 140,
    source: 'score',
    round_winner: 'maproom',
    is_calibration: false,
    timestamp: '2025-01-05T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R05',
    competitor: 'explore',
    round_type: 'regular',
    codebase: 'mattermost-webapp',
    phase: 1,
    query_category: 'lifecycle',
    precision: 2,
    recall: 2,
    insight: 2,
    total: 6,
    calls: 30,
    time_s: 220,
    source: 'score',
    round_winner: 'maproom',
    is_calibration: false,
    timestamp: '2025-01-05T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R06',
    competitor: 'maproom',
    round_type: 'regular',
    codebase: 'mattermost-webapp',
    phase: 1,
    query_category: 'error-handling',
    precision: 2,
    recall: 3,
    insight: 2,
    total: 7,
    calls: 14,
    time_s: 110,
    source: 'score',
    round_winner: null,
    is_calibration: false,
    timestamp: '2025-01-06T10:00:00Z',
  },
  {
    schema_version: 1,
    round_id: 'R06',
    competitor: 'explore',
    round_type: 'regular',
    codebase: 'mattermost-webapp',
    phase: 1,
    query_category: 'error-handling',
    precision: 3,
    recall: 2,
    insight: 2,
    total: 7,
    calls: 16,
    time_s: 130,
    source: 'score',
    round_winner: null,
    is_calibration: false,
    timestamp: '2025-01-06T10:00:00Z',
  },
];
